"""TenderFlow Guinea — GeneratedDocument Model."""
from datetime import datetime
from uuid import uuid4

from sqlalchemy import String, Boolean, DateTime, ForeignKey, Text, Integer

from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class GeneratedDocument(Base):
    """Document generated by the AI for a tender."""
    __tablename__ = "generated_documents"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    tenant_id: Mapped[str] = mapped_column(String(36), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True)
    tender_id: Mapped[str | None] = mapped_column(String(36), ForeignKey("tenders.id", ondelete="CASCADE"), nullable=True, index=True)

    document_type: Mapped[str] = mapped_column(String(100), nullable=False)
    # Types: technical_memo / financial_offer / checklist / conformity_matrix /
    # opportunity_sheet / crm_export / presentation / custom

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    format: Mapped[str] = mapped_column(String(20), default="md")  # docx / pdf / md / json

    storage_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    file_size: Mapped[int | None] = mapped_column(Integer, nullable=True)

    is_exported: Mapped[bool] = mapped_column(Boolean, default=False)
    version: Mapped[int] = mapped_column(Integer, default=1)

    created_by: Mapped[str | None] = mapped_column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    tender = relationship("Tender", back_populates="generated_documents")

    def __repr__(self) -> str:
        return f"<GeneratedDocument {self.document_type}: {self.title[:50]}>"
